[package]
name = "quantcast"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.34", features = ["serde"] }
clap = { version = "4.5.1", features = ["derive", "cargo"] }
csv = "1.3.0"
serde = { version = "1.0.197", features = ["derive"] }
tempfile = "3.10.1"
